name: Release VSIX

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on semver tags like v1.0.0

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js  # Use Node 22 LTS for compatibility
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install vsce globally
        run: npm install -g @vscode/vsce

      - name: Get version from package.json
        id: get_version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Package extension
        run: vsce package

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload VSIX to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./prpl-theme-${{ steps.get_version.outputs.version }}.vsix
          asset_name: prpl-theme-${{ steps.get_version.outputs.version }}.vsix
          asset_content_type: application/octet-stream
